name: Stress Tests
on:
  push:

env:
  OS: ubuntu-24.04
  ARCH: x86_64
  CIBW_SYSTEM: manylinux
  PYTHON_VERSION: cp313
  TESTSUITE: fast
  ITERATIONS: 3



jobs:
  build:
    name: "Build wheel: cp313-manylinux_x86_64"
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout DuckDB Python
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.16"
          enable-cache: false
          cache-suffix: -${{ env.PYTHON_VERSION }}-${{ env.OS }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Export test requirements
        shell: bash
        run: |
          uv export --only-group test --no-emit-project --output-file test-requirements.txt --quiet

      - name: Build wheel
        uses: pypa/cibuildwheel@v3.1
        env:
          CIBW_ARCHS: ${{ env.ARCH }}
          CIBW_BUILD: ${{ env.PYTHON_VERSION }}-${{ env.CIBW_SYSTEM }}_${{ env.ARCH }}
          CIBW_TEST_SKIP: '*'
          # Platform-specific ccache installation commands
          CIBW_BEFORE_BUILD_LINUX: ""
          CIBW_BEFORE_BUILD_MACOS: ""
          CIBW_BEFORE_BUILD_WINDOWS: ""

      - name: Upload test requirements
        uses: actions/upload-artifact@v4
        with:
          name: test-requirements-${{ env.PYTHON_VERSION }}-${{ env.CIBW_SYSTEM }}_${{ env.ARCH }}
          path: test-requirements.txt

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ env.PYTHON_VERSION }}-${{ env.CIBW_SYSTEM }}_${{ env.ARCH }}
          path: wheelhouse/

  test:
    name: 'Test: ${{ matrix.pytest_config.name }} - cp313-manylinux_x86_64'
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        pytest_config:
          - name: "Random Order"  # randomization is automatic due to pytest-randomly
            args: ""
            iterations: 3
          - name: "Multiprocess"  # uses pytest-xdist
            args: "-n auto"
            iterations: 3
          - name: "Threaded"  # uses pytest-run-parallel
            # TODO: Update to use threading specific tests or explicitly mark unsafe tests. test_module was chosen as an example.
            args: "--parallel-threads=4 --iterations=8 tests/fast/test_module.py --ignore"
            iterations: 1

    steps:
      - name: Checkout test files only
        uses: actions/checkout@v4
        with:
          sparse-checkout: tests
          sparse-checkout-cone-mode: false

      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.16"
          enable-cache: true
          activate-environment: true
          cache-suffix: -${{ env.PYTHON_VERSION }}-${{ env.OS }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel-${{ env.PYTHON_VERSION }}-${{ env.CIBW_SYSTEM }}_${{ env.ARCH }}
          path: wheelhouse/

      - name: Download test requirements
        uses: actions/download-artifact@v4
        with:
          name: test-requirements-${{ env.PYTHON_VERSION }}-${{ env.CIBW_SYSTEM }}_${{ env.ARCH }}
          path: .

      - name: Install dependencies
        shell: bash
        run: |
          rm -f pyproject.toml  # Remove any project metadata to prevent build attempts
          uv pip install -r test-requirements.txt
          uv pip install wheelhouse/*.whl --no-deps --force-reinstall

      - name: Run ${{ matrix.pytest_config.name }} tests
        shell: bash
        run: |
          TEST_TARGET="tests/fast"
          ITERATIONS="${{ matrix.pytest_config.iterations }}"
          PYTEST_ARGS="${{ matrix.pytest_config.args }}"

          echo "Running ${{ matrix.pytest_config.name }} pytest $ITERATIONS times against: $TEST_TARGET"
          for i in $(seq 1 $ITERATIONS); do
            echo ""
            echo "${{ matrix.pytest_config.name }} Run $i/$ITERATIONS:"
            echo "--------"
            uv run pytest $PYTEST_ARGS "$TEST_TARGET" --durations=5
            if [ $? -ne 0 ]; then
              echo "${{ matrix.pytest_config.name }} Run $i failed!"
            else
              echo "${{ matrix.pytest_config.name }} Run $i passed!"
            fi
          done