name: Tests and coverage on push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if:  false # ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == true }}
    name: Run coverage tests
    uses: ./.github/workflows/coverage.yml
    with:
      git_ref: ${{ github.ref }}
      testsuite: fast
