name: Packaging
run-name: Build ${{ inputs.minimal && 'minimal set of' || 'all' }} packages (version=${{ inputs.set-version != '' && inputs.set-version || 'dev' }}, tests=${{ inputs.testsuite }}, ref=${{ inputs.git-ref }}, duckdb ref=${{ inputs.duckdb-git-ref }})
on:
  workflow_dispatch:
    inputs:
      minimal:
        type: boolean
        description: Build a minimal set of wheels to do a sanity check
        default: false
      testsuite:
        type: choice
        description: Testsuite to run (none, fast, all)
        required: true
        default: all
        options:
          - none
          - fast
          - all
      duckdb-python-sha:
        type: string
        description: The commit to build against (defaults to latest commit of current ref)
        required: false
      duckdb-sha:
        type: string
        description: Override the DuckDB submodule commit or ref to build against
        required: false
      set-version:
        type: string
        description: Force version (vX.Y.Z-((rc|post)N))
        required: false
  workflow_call:
    inputs:
      minimal:
        type: boolean
        description: Build a minimal set of wheels to do a sanity check
        default: false
      testsuite:
        type: string
        description: Testsuite to run (none, fast, all)
        required: true
        default: all
      duckdb-python-sha:
        type: string
        description: The commit or ref to build against (defaults to latest commit of current ref)
        required: false
      duckdb-sha:
        type: string
        description: Override the DuckDB submodule commit or ref to build against
        required: false
      set-version:
        description: Force version (vX.Y.Z-((rc|post)N))
        required: false
        type: string

concurrency:
  group: packaging-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_sdist:
    name: Build an sdist and determine versions
    uses: ./.github/workflows/packaging_sdist.yml
    with:
      testsuite: all
      duckdb-python-sha: ${{ inputs.duckdb-python-sha != '' && inputs.duckdb-python-sha || github.sha }}
      duckdb-sha: ${{ inputs.duckdb-sha }}
      set-version: ${{ inputs.set-version }}

  build_wheels:
    name: Build and test releases
    uses: ./.github/workflows/packaging_wheels.yml
    with:
      minimal: false
      testsuite: all
      duckdb-python-sha: ${{ inputs.duckdb-python-sha != '' && inputs.duckdb-python-sha || github.sha }}
      duckdb-sha: ${{ inputs.duckdb-sha }}
      set-version: ${{ inputs.set-version }}
